### ISSUE TITLE
IE7 Broken

### ISSUE THREAD

**Issue by ryanrphillips** [tutorialzine/touchTouch#18]
Hey,

I know IE7 isn't supported with this plugin, but is there anyway it can be updated to not look completely broken? Even if it had no animation and just loaded the next image or something?

It seems to load the first image fine (though not vertically centred which isn't a big issue for us) but the rest don't seem to be there? Some debugging shows they seem to load underneath each other and all disappear when you click Next.

Not sure what else we can do to fix it, so hopefully you guys could figure something out.

Thanks.

**Comment by designcouch** [comment]
Why in the world are you coding for IE7? Seems to be the standard practice to code for the 3 most current versions (and right now, that's IE8, 9 and 10). At this point, offering even rudimentary support for it would mean abandoning even the basic possibilities of CSS3 and HTML5 (which this plugin uses pretty extensively). If you want compatibility with IE7, I would recommend using a conditional statement to load a different, simpler lightbox that is better supported (like the original lightbox script written by Lokesh Dhakar).

**Comment by ryanrphillips** [comment]
I'd rather not be coding for IE7 - it's terrible. But we have to, as a large part of our client-base still use it.

Thanks for the suggestion, but we've opted for a simpler lightbox across all browsers.
