### ISSUE TITLE
No navigation on iPod Touch

### ISSUE THREAD

**Issue by fredfletcher** [tutorialzine/touchTouch#2]
Great script and I love the look, yet there is no navigation capabilities (arrows etc) when seeing the gallery/photos on the iPod Touch.

Any suggestions on how to achieve this, or is this a probable bug?

Cheers!

Fred

**Comment by martinaglv** [comment]
The arrows are only shown on desktop browsers (where touch is not supported). On the ipod you can swipe to navigate the gallery.
